# Site settings
title: Max Equation
email: fedmysoul@gmail.com
description: The life and work of Max Equation.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fedmysoul.github.io/" # the base hostname & protocol for your site
twitter_username: fedmysoul
github_username:  fedmysoul

# Build settings
markdown: kramdown
